Use Python stack for scraper
FIRSTMap/scraper pull request #9
Opened 2020-12-18 20:47 UTC by EthShaw

Rewrote the gawk/bash scraper scripts in Python. I updated the Readme with the new changes. When rewriting the README, I noticed that the TBA-auth file is not supposed to be included in the repository. Since it makes sense that the TBA key should not be redistributed, I removed it from the repository and added some instructions explaining an overview of how to get one from thebluealliance.com. I also made sure the program creates a descriptive warning if this file does not exist. The new scraper.py replaces all of the old scripts except ask_google, which I did not change.

Fixes issue #7

2020-12-18 20:52 UTC, ErikBoesen requested changes

2020-12-18 20:52 UTC, ErikBoesen commented on README.md
> +**README.md** - This file.
I feel like you can probably just omit this

2020-12-18 20:52 UTC, ErikBoesen commented on README.md
> +**[explanation of process.md](explanation%20of%20process.md)** - This file
Can we merge this into this README? Or at the very least, give it a name without spaces?

2020-12-18 20:52 UTC, ErikBoesen commented
Amazing work. Thank you so much.

2020-12-18 21:08 UTC, ErikBoesen requested changes
I know this is a lot of comments, but this is still excellent work, and most of these complaints are quite minor.

2020-12-18 21:08 UTC, ErikBoesen commented on explanation of process.md
> +            - \[Lines 115-117\]: If the `country` is `"MX"` and the `prov` is `"DISTRITO FEDERAL"`, set `prov` to `"MEXICO CITY"`.
Do we need to document every single line? If so, could we do it more effectively with inline comments?

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +MIT License
I prefer to include licenses in a separate `LICENSE` file rather than inline.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +AUTH_PATH = Path('TBA-auth')
I would prefer a cleaner filename, such as `tba_token.txt`, `token.txt`, or something to that effect

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +if not AUTH_PATH.exists():
I usually just use `os.path.exists` for this purpose, since it's more native

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    print('You must generate a Read API authorization key on The Blue')
Maybe just make this a one-line message and log it all together rather than manually separating it across lines.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +# Load the lear from the YEAR file
*year

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +CACHE_DIR = Path.cwd() / 'cache'
Is this syntax allowed with the `Path` module? Seems a little strange.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +# countries listed as Czechia Prague and Taiwan, respectively.
"Czechia Prague" lol

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +teamData = None
snake_case please

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +useCache = False
Snake case

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    global useCache
I would prefer to avoid global variables.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    [ 'https://download.geonames.org/export/zip/allCountries.zip',       'allCountries.zip',     True  ],
Make this a dict instead of an array of arrays. It'll be easier to iterate.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    for file in POSTAL_FILES:
Consider expanding this, such as:
```py
for url, filename, needs_unzip in POSTAL_FILES:
    ...
```
(You'll need to adjust if you use my array suggestion.)

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    [ 'https://download.geonames.org/export/zip/allCountries.zip',       'allCountries.zip',     True  ],
Alternatively, at least make them tuples.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +                    for chunk in req.iter_content(chunk_size=16384):
Can we make a constant for this chunk size rather than the magic number?

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    """ Definitions """
Weird comment format

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    def readTSV(file, callback, sep='\t'):
Snake case again

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +                row = line.split(sep)
Do you want to strip this before splitting it?

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    """ Initialize the country codes table """
Again, would prefer # style comment

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    print ('Loading country code mappings...')
Remove the space between `print` and `(`

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +    """
Comment styling

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +        Initialize the cities dictionary, which holds the lattitude and
*latitude

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +        cityNameAscii = row[2].upper()
Snake case for all this stuff

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +        # This helper function puts the lattitude and longitude of the city
*latitude

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +            province = 'HENAN'
❗  Hunan and Henan are two separate provinces.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +                city = "LEE'S SUMMIT"
I generally prefer sticking with the standardized single quotes and escaping the apostrophe, but that's just me.

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +            elif province =='MO' and city == 'LEES SUMMIT':
Missing a space between `==` and `'MO'`

2020-12-18 21:08 UTC, ErikBoesen commented on scraper.py
> +            province = 'NACIONAL'
Could there be a better way to specify these replacements? Like a JSON file that can specify in a standard format so you can iterate through and do all the replacements without having to hardcode them? Just a thought, not a blocker.

2020-12-18 21:10 UTC, ErikBoesen commented on scraper.py
> +CACHE_DIR = Path.cwd() / 'cache'
This isn't an issue, more just a comment as I'm unfamiliar with this pretty neat syntax

2020-12-18 21:11 UTC, ErikBoesen commented on scraper.py
> +    [ 'https://download.geonames.org/export/zip/allCountries.zip',       'allCountries.zip',     True  ],
tbh, if you wanted to make a class for these that could also be neat.

2020-12-21 17:20 UTC, EthShaw commented on scraper.py
> +            province = 'HENAN'
Interesting. I wonder why this was in the original script. It doesn't seem to break anything when I remove it.

2020-12-21 23:46 UTC, EthShaw commented on README.md
> +**[explanation of process.md](explanation%20of%20process.md)** - This file
Honestly, I don't know why I included the file. I mostly made it when dissecting the original gawk script so it would be easier to rewrite it. I could just delete it and merge the part that pertains to the current version into the README.

2020-12-22 00:40 UTC, ErikBoesen commented on README.md
> +**[explanation of process.md](explanation%20of%20process.md)** - This file
That would be ideal!

2020-12-22 18:15 UTC, EthShaw commented on scraper.py
> +# countries listed as Czechia Prague and Taiwan, respectively.
As it turns out, my comment is actually incorrect. I thought it was strange, and I looked back and realized I must have mistaken a tab for a space (it was only 1 character width because of the alignment). It's actually only listed as "Czechia" in the GeoNames database.

2020-12-22 18:31 UTC, EthShaw commented on scraper.py
> +                row = line.split(sep)
The original scraper doesn't strip the lines before splitting, so as far as I am aware it isn't necessary. The reason for the lstrip before the # check is in case any of the lines with comments have leading spaces. In the original scraper, comments were just treated like all the other lines, but lines that didn't have enough columns after splitting on \t were ignored, which effectively eliminated the comments since none of them contained tabs. Do you think I should strip the lines before splitting them?

2020-12-22 18:42 UTC, EthShaw commented on scraper.py
> +CACHE_DIR = Path.cwd() / 'cache'
Yes, this is valid syntax. The `pathlib` library overrides the `/` operator per [https://docs.python.org/3/library/pathlib.html#operators](https://docs.python.org/3/library/pathlib.html#operators). I don't have a lot of experience with Python, so I found this when I was looking at how to do file and path manipulation. It is a pretty neat and concise syntax.

2020-12-22 19:04 UTC, EthShaw commented on scraper.py
> +if not AUTH_PATH.exists():
What are the differences between `os.path.exists` and `pathlib`'s `Path.exists`?

2020-12-23 14:11 UTC, ErikBoesen commented on scraper.py
> +                row = line.split(sep)
I misremembered how `.split()` works, disregard.

2020-12-23 14:11 UTC, ErikBoesen commented on scraper.py
> +if not AUTH_PATH.exists():
Probably not much. Since you've standardized on using `pathlib` in this script, probably fine to stick with that.

2020-12-23 14:12 UTC, ErikBoesen commented on scraper.py
> +CACHE_DIR = Path.cwd() / 'cache'
Very neat!

2020-12-23 21:06 UTC, EthShaw commented on scraper.py
> +            province = 'NACIONAL'
I might address this in a separate PR.

2020-12-23 21:11 UTC, EthShaw commented
I believe I addressed all of your comments. Just a note, the scraper indents `teams.json` with tabs. I chose this because it uses less bytes each line, but the original uses three spaces, so I can switch to that (or another number of spaces) if you would prefer.

2020-12-23 21:45 UTC, ErikBoesen commented on scraper.py
> +            province = 'NACIONAL'
That's fine.

2020-12-23 21:51 UTC, ErikBoesen requested changes
Almost there.

2020-12-23 21:51 UTC, ErikBoesen commented on scraper.py
> +    def proccess_cities(row):
*process

2020-12-23 21:51 UTC, ErikBoesen commented on scraper.py
> +        admin_name_ascii = geo_names['adms'].get(
I don't think this needs to be on two lines

2020-12-23 21:51 UTC, ErikBoesen commented on scraper.py
> +    """A helper class to hold the url and name of a GeoNames file as
For a multi-line docstring, the convention is to put the """s on separate lines from the content of the docstring.
```py
"""
A helper class
etc.
"""
```

2020-12-23 21:51 UTC, ErikBoesen commented on scraper.py
> +    def proccess_admin_codes(row):
*process again here

2020-12-24 17:04 UTC, ErikBoesen approved these changes

2020-12-24 17:04 UTC, merged

2020-12-24 17:04 UTC, ErikBoesen commented
Thank you!